image: gcc:6
#image: debian:stretch

stages:
    - build

variables:
    ION_VERSION: '3.6.2'
    DTN2_VERSION: '2.9.0'
    OASYS_VERSION: '1.6.0'
    ion_build_url: 'https://gitlab.com/michirod/ion-build'
    dtn2_build_url: 'https://gitlab.com/michirod/dtn2-build'

al_bp:
    stage: build
    script:
        - wget -O ion-${ION_VERSION}.zip ${ion_build_url}/-/jobs/artifacts/${ION_VERSION}/download?job=build
        - wget -O dtn2-${DTN2_VERSION}.zip ${dtn2_build_url}/-/jobs/artifacts/${DTN2_VERSION}/download?job=build
          #- curl -o ion-${ION_VERSION}.zip ${ion_build_url}/-/jobs/artifacts/${ION_VERSION}/download?job=build
          #- curl -o dtn2-${DTN2_VERSION}.zip ${dtn2_build_url}/-/jobs/artifacts/${DTN2_VERSION}/download?job=build
        - unzip ion-${ION_VERSION}.zip
        - unzip dtn2-${DTN2_VERSION}.zip
        - cp -rv package-*/* /
        - make ION_DIR=ion/ion-${ION_VERSION} DTN2_DIR=dtn2/dtn-${DTN2_VERSION}
